export default [{
    title: "The family at the beach",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Brian", "Gloria"],
    location: "beach",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/beach.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/beach.jpg",
}, {
    title: "Playing at the beach",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Gloria"],
    location: "beach",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/beach_1.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/beach_1.jpg",
}, {
    title: "Playing at the pool",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Brian", "Gloria"],
    location: "beach",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/beach_2.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/beach_2.jpg",
}, {
    title: "Sledding in Arkansas",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Brian", "Gloria", "Glenda", "Garrett", "Berta", "Celyna", "Ray"],
    location: "arkansas",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/arkansas-sledding.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/arkansas-sledding.jpg",
}, {
    title: "Church Kid's Concert",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Brian"],
    location: "church",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/church.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/church.jpg",
}, {
    title: "Emily's Graduation",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Emily"],
    location: "school",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/emily-graduation.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/emily-graduation.jpg",
}, {
    title: "Holidays",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Brian", "Ray", "Gloria"],
    location: "home",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/halloween.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/halloween.jpg",
}]