export default [{
    title: "The family at the beach",
    year: "unknown",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Brian", "Gloria"],
    location: "beach",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/beach.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/beach.jpg",
}, {
    title: "Playing at the beach",
    year: "90",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Gloria"],
    location: "beach",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/beach_1.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/beach_1.jpg",
}, {
    title: "Playing at the pool",
    year: "91",
    keywords: ["key", "word"],
    stars: ["Tim", "Emily", "Brian", "Gloria"],
    location: "beach",
    url: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/beach_2.mp4",
    thumbnailUrl: "https://assets.corneliuses.com/videos/family/Home-movies/unknown/thumbnails/beach_2.jpg",
}]